version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db_local
    ports:
    - 5432:5432

  restmicroservice:
    container_name: restmicroservice
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres